### ISSUE TITLE
Serving new site fails with Liquid Exception: Failed to get header...

### ISSUE THREAD

**Issue by frosforever** [jekyll/docker-jekyll#24]
Following the basic getting started for Jekyll but modified for the use with the docker image, in a fresh directory I have run 
```bash
docker run -it --rm --label=jekyll --label=stable --volume=$(pwd):/srv/jekyll -p 4000:4000 jekyll/stable jekyll new .
```
This creates the standard directory layout
   
    _config.yml	 _layouts	_sass		css		index.html _includes	_posts		about.md	feed.xml

I then run
```bash
docker run -it --rm --label=jekyll --label=stable --volume=$(pwd):/srv/jekyll -p 4000:4000 jekyll/stable jekyll serve -t
```

And receive an error:
```
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
      Generating... 
  Liquid Exception: Failed to get header. in _posts/2015-08-15-welcome-to-jekyll.markdown
/usr/lib/ruby/gems/2.2.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:381:in `rescue in get_header': Failed to get header. (MentosError)
	from /usr/lib/ruby/gems/2.2.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:362:in `get_header'
	from /usr/lib/ruby/gems/2.2.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:259:in `block in mentos'
	from /usr/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /usr/lib/ruby/2.2.0/timeout.rb:34:in `block in catch'
	from /usr/lib/ruby/2.2.0/timeout.rb:34:in `catch'
	from /usr/lib/ruby/2.2.0/timeout.rb:34:in `catch'
	from /usr/lib/ruby/2.2.0/timeout.rb:104:in `timeout'
	from /usr/lib/ruby/gems/2.2.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:233:in `mentos'
	from /usr/lib/ruby/gems/2.2.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:215:in `highlight'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/tags/highlight.rb:82:in `render_pygments'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/tags/highlight.rb:52:in `render'
	from /usr/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:109:in `block in render_all'
	from /usr/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:96:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:96:in `render_all'
	from /usr/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/block.rb:82:in `render'
	from /usr/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/template.rb:128:in `render'
	from /usr/lib/ruby/gems/2.2.0/gems/liquid-2.6.3/lib/liquid/template.rb:138:in `render!'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:106:in `render_liquid'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:233:in `do_layout'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/post.rb:261:in `render'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/lib/ruby/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

A quick search (forgive my complete ignorance of jekyll, this is the first I'm using it) seems to indicate that this error might be related to a python installation. When I run `jekyll doctor` I get the all clear.

Is the docker image missing something needed to get started?
Does the standard getting started with jekyll not apply if using docker?

`docker images` output:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
jekyll/stable       latest              92cf689c674c        3 days ago          92.31 MB
```

**Comment by frosforever** [comment]
It seems that python 2.7 is removed from the container in the [Dockerfile](https://github.com/jekyll/docker-jekyll/blob/master/Dockerfile#L39) but is needed for Pygments to run.
If it's common for people to use Pygments with Jekyll (it's in the default generated site) perhaps python should be left in the container. Alternatively, this could be mentioned in the docs such that people getting started know they have to add python to their own container.

**Comment by envygeeks** [comment]
It's already been fixed, I just haven't pushed it.

**Comment by frosforever** [comment]
@envygeeks bravo! 
Finally got some time to do some more digging and it's already fixed.

**Comment by envygeeks** [comment]
Fixed by: https://github.com/jekyll/docker-jekyll/commit/c6b31655f0b5795b29b03cd8bc3c50cc05f56889
