### ISSUE TITLE
Getting error when runnning

### ISSUE THREAD

**Issue by geshan** [jekyll/docker-jekyll#25]
Got the following error with the command 

```
docker run --rm --label=jekyll --label=stable --volume=$(pwd):/srv/jekyll \
  -t -p 127.0.0.1:4000:4000 jekyll/stable jekyll s

```

## Error

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20150821-15-763lna.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20150821-15-d9pl7uffi-1.9.6/gems/ffi-1.9.6 for inspection.
Results logged to /tmp/bundler20150821-15-d9pl7uffi-1.9.6/extensions/x86_64-linux/2.2.0/ffi-1.9.6/gem_make.out

```

**Comment by envygeeks** [comment]
That doesn't help, please post the full log not just part of it.

**Comment by envygeeks** [comment]
Also is the source to your site available? Do you use a Gemfile?

**Comment by geshan** [comment]
here is the full log:

```
docker run --rm --label=jekyll --label=stable --volume=$(pwd):/srv/jekyll \
>   -t -p 127.0.0.1:4000:4000 jekyll/stable jekyll s
Unable to find image 'jekyll/stable:latest' locally
latest: Pulling from jekyll/stable
61d7c22bd37c: Pull complete 
4505485910c7: Pull complete 
a0e47c779cc0: Pull complete 
864c2ab00ff6: Pull complete 
93f480fde60d: Pull complete 
f99c1c741b40: Pull complete 
51163470672b: Pull complete 
a6db5fb24646: Pull complete 
7bda41bc0fe7: Pull complete 
3a1dd465c987: Already exists 
5e704a9ae9ac: Already exists 
Digest: sha256:f46eedcb69470c4f41ebd2f5a05de84bbf9e8c21f9a24fd8c4f16f69e486cbfd
Status: Downloaded newer image for jekyll/stable:latest
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using blankslate 2.1.2.4
Using hitimes 1.2.2
Installing timers 4.0.1
Installing celluloid 0.16.0
Using fast-stemmer 1.0.2
Using classifier-reborn 2.0.3
Installing coffee-script-source 1.9.1
Installing execjs 2.3.0
Installing coffee-script 2.3.0
Using colorator 0.1
Installing ffi 1.9.6 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20150821-15-i3z70s.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20150821-15-u0dwkffi-1.9.6/gems/ffi-1.9.6 for inspection.
Results logged to /tmp/bundler20150821-15-u0dwkffi-1.9.6/extensions/x86_64-linux/2.2.0/ffi-1.9.6/gem_make.out
An error occurred while installing ffi (1.9.6), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.6'` succeeds before bundling.

```

site source: https://github.com/younginnovations/blog.yipl.com.np

**Comment by envygeeks** [comment]
Looks like this was a bug in the helpers that was previously fixed but not pushed out since we are adjusting images to use the new Docker 1.8 signed images, I'll accelerate that push for our Alpine images and update this image today so this can be resolved.

**Comment by geshan** [comment]
Thank you so much for the update.

**Comment by geshan** [comment]
If you have any information please update.

**Comment by envygeeks** [comment]
This is fixed now with the latest rebuild.

**Comment by geshan** [comment]
now I got this error : 

```
 docker run --rm --label=jekyll --label=stable --volume=$(pwd):/srv/jekyll \
>   -it -p 127.0.0.1:4000:4000 jekyll/stable jekyll s
/usr/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find coffee-script-source-1.9.1 in any of the sources (Bundler::GemNotFound)
	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `map!'
	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize'
	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for'
	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/definition.rb:174:in `requested_specs'
	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/environment.rb:18:in `requested_specs'
	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:13:in `setup'
	from /usr/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:37:in `require_from_bundler'
	from /usr/lib/ruby/gems/2.2.0/gems/jekyll-2.5.3/bin/jekyll:16:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'

```
I have pulled the latest image.

**Comment by envygeeks** [comment]
That's because you provide a Gemfile without all the dependencies you need and without using bundle exec, you need to fix your Gemfile and use bundle exec.
